/**
 * Session controller — NTM-inspired tmux orchestration for Foreman.
 *
 * Replaces the ad-hoc tmux management in policy.ts with a proper
 * session lifecycle controller. Inspired by NTM's robot mode.
 *
 * Capabilities:
 *   spawn(project, prompt)     — start interactive claude in tmux
 *   send(session, prompt)      — inject follow-up prompt into running session
 *   status()                   — JSON status of all sessions
 *   inspect(session, opts)     — read session output with pattern matching
 *   metrics(session)           — commits, lines, tests per session
 *   kill(session)              — stop a session
 *   detectContextExhaustion()  — check for "prompt too long" in output
 */

import { execFileSync } from 'node:child_process'
import { mkdirSync, writeFileSync, readFileSync, existsSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { homedir } from 'node:os'

const FOREMAN_HOME = process.env.FOREMAN_HOME ?? join(homedir(), '.foreman')
const CLAUDE_BIN = process.env.CLAUDE_PATH ?? '/home/drew/.local/bin/claude'
const ENV = { ...process.env, PATH: `${process.env.HOME}/.local/bin:${process.env.PATH}` }

// ─── Types ──────────────────────────────────────────────────────────

export interface SessionInfo {
  name: string
  project: string
  projectPath: string
  alive: boolean
  round: number
  totalCommits: number
  lastActivity: string | null
  logFile: string
  progressFile: string
}

export interface SessionMetrics {
  commits: number
  linesAdded: number
  linesRemoved: number
  filesChanged: number
  testsAdded: number
  rounds: number
}

export interface InspectOptions {
  lastN?: number
  pattern?: string
  codeOnly?: boolean
}

// ─── Helpers ────────────────────────────────────────────────────────

function sessionName(project: string): string {
  const name = project.split('/').pop() ?? project
  return `foreman-${name}`.replace(/[^a-zA-Z0-9_-]/g, '-').slice(0, 40)
}

function tmuxRun(args: string[], options?: { encoding?: 'utf8'; timeout?: number }): string {
  return execFileSync('tmux', args, {
    encoding: options?.encoding ?? 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
    timeout: options?.timeout ?? 5_000,
    env: ENV,
  }) as string
}

function tmuxRunQuiet(args: string[]): boolean {
  try {
    execFileSync('tmux', args, { stdio: 'ignore', timeout: 5_000, env: ENV })
    return true
  } catch {
    return false
  }
}

function gitStat(cwd: string): { commits: number; linesAdded: number; linesRemoved: number; filesChanged: number } {
  try {
    const log = execFileSync('git', ['log', '--oneline'], { cwd, encoding: 'utf8', timeout: 5_000 })
    const commits = log.trim().split('\n').filter(Boolean).length

    const diff = execFileSync('git', ['diff', '--shortstat', 'HEAD~1..HEAD'], { cwd, encoding: 'utf8', timeout: 5_000, stdio: ['ignore', 'pipe', 'ignore'] }).trim()
    const filesMatch = diff.match(/(\d+) file/)
    const addMatch = diff.match(/(\d+) insertion/)
    const delMatch = diff.match(/(\d+) deletion/)

    return {
      commits,
      linesAdded: addMatch ? parseInt(addMatch[1]) : 0,
      linesRemoved: delMatch ? parseInt(delMatch[1]) : 0,
      filesChanged: filesMatch ? parseInt(filesMatch[1]) : 0,
    }
  } catch {
    return { commits: 0, linesAdded: 0, linesRemoved: 0, filesChanged: 0 }
  }
}

// ─── Project context ────────────────────────────────────────────────

function findProjectContext(projectPath: string): string | null {
  const candidates = [
    join(projectPath, '..', '..'),
    join(projectPath, '..'),
    projectPath,
  ]
  for (const dir of candidates) {
    try {
      const files = readdirSync(dir)
      const contextFile = files.find((f: string) =>
        (f.endsWith('.txt') && f.length > 5) ||
        f.endsWith('_master.md') ||
        f === 'context.md' ||
        f === 'SPEC.md',
      )
      if (contextFile) return join(dir, contextFile)
    } catch {}
  }
  return null
}

function ensureClaudeMd(projectPath: string): void {
  const claudeMdPath = join(projectPath, 'CLAUDE.md')
  if (existsSync(claudeMdPath)) return

  const contextFile = findProjectContext(projectPath)
  if (!contextFile) return

  const raw = readFileSync(contextFile, 'utf8').slice(0, 3000)
  writeFileSync(claudeMdPath, `# Project Context (auto-generated by Foreman)

## Source
Extracted from the original design document.

## Summary
${raw}

## Working Rules
- Write code, don't just analyze
- Commit frequently with descriptive messages
- Run tests after every change
- Fix failures before moving on
- Keep implementations succinct — no bloat
`, 'utf8')
}

// ─── Core: spawn ────────────────────────────────────────────────────

export function spawn(projectPath: string, prompt?: string): SessionInfo {
  const name = sessionName(projectPath)

  if (isAlive(name)) {
    return getSessionInfo(name, projectPath)
  }

  mkdirSync(join(FOREMAN_HOME, 'tmp'), { recursive: true })
  mkdirSync(join(FOREMAN_HOME, 'logs'), { recursive: true })

  // Inject project context
  ensureClaudeMd(projectPath)

  // Create tmux session
  tmuxRunQuiet(['new-session', '-d', '-s', name, '-c', projectPath])

  // Capture output to log
  const logFile = join(FOREMAN_HOME, 'logs', `session-${name}.log`)
  tmuxRunQuiet(['pipe-pane', '-t', name, `-o cat >> ${logFile}`])

  // Send initial prompt (or default build prompt)
  const actualPrompt = prompt ?? buildPrompt(projectPath, 1)
  sendPrompt(name, actualPrompt)

  return getSessionInfo(name, projectPath)
}

// ─── Core: send ─────────────────────────────────────────────────────

export function send(nameOrProject: string, prompt: string): boolean {
  const name = nameOrProject.startsWith('foreman-') ? nameOrProject : sessionName(nameOrProject)
  if (!isAlive(name)) return false
  return sendPrompt(name, prompt)
}

function sendPrompt(name: string, prompt: string): boolean {
  // Write prompt to temp file to avoid shell escaping issues
  const promptFile = join(FOREMAN_HOME, 'tmp', `${name}-prompt.txt`)
  writeFileSync(promptFile, prompt, 'utf8')

  // Send claude -p command to the tmux session
  return tmuxRunQuiet([
    'send-keys', '-t', name,
    `${CLAUDE_BIN} -p "$(cat ${promptFile})" --output-format text --dangerously-skip-permissions`, 'Enter',
  ])
}

function buildPrompt(projectPath: string, round: number): string {
  const stateFile = join(projectPath, '.foreman', 'session-state.md')
  let context = ''
  if (existsSync(stateFile)) {
    context = `Previous session state:\n${readFileSync(stateFile, 'utf8').slice(0, 1500)}\n\n`
  }

  return `${context}You are an autonomous coding agent. Round ${round}. You have FULL permission to edit any file, run any command, and commit. Do NOT ask for permission. Do NOT ask "should I?" or "want me to?" — just DO IT.

Read CLAUDE.md for project context. Read .foreman/session-state.md for previous work.

Execute this sequence:
1. Install dependencies (npm install / pip install / etc)
2. Run tests or type checks
3. Fix every failure you find
4. Identify the most broken or incomplete part of the codebase
5. Fix it completely — write the code, write tests, verify they pass
6. git add and git commit with a descriptive message
7. Write .foreman/session-state.md with: what you did, what failed, what's next
8. If time remains, go back to step 2

NEVER ask questions. NEVER just analyze. ALWAYS write code and commit.`
}

// ─── Core: status (robot mode) ──────────────────────────────────────

export function status(): SessionInfo[] {
  const sessions: SessionInfo[] = []
  try {
    const out = tmuxRun(['list-sessions', '-F', '#{session_name}:#{session_path}'])
    for (const line of out.trim().split('\n')) {
      if (!line.startsWith('foreman-')) continue
      const [name] = line.split(':')
      const info = getSessionInfo(name)
      sessions.push(info)
    }
  } catch {}
  return sessions
}

function getSessionInfo(name: string, projectPath?: string): SessionInfo {
  const path = projectPath ?? resolveProjectFromSession(name)
  const logFile = join(FOREMAN_HOME, 'logs', `session-${name}.log`)
  const progressFile = join(FOREMAN_HOME, 'logs', `progress-${name}.log`)

  let round = 0
  try {
    const log = readFileSync(logFile, 'utf8')
    const rounds = log.match(/=== Round (\d+)/g)
    if (rounds) round = rounds.length
  } catch {}

  const git = gitStat(path)

  return {
    name,
    project: path.split('/').pop() ?? name,
    projectPath: path,
    alive: isAlive(name),
    round,
    totalCommits: git.commits,
    lastActivity: new Date().toISOString(),
    logFile,
    progressFile,
  }
}

function resolveProjectFromSession(name: string): string {
  try {
    const out = tmuxRun(['display-message', '-t', name, '-p', '#{pane_current_path}'])
    return out.trim()
  } catch {
    return join(homedir(), 'code', name.replace('foreman-', ''))
  }
}

// ─── Core: inspect ──────────────────────────────────────────────────

export function inspect(nameOrProject: string, options?: InspectOptions): string {
  const name = nameOrProject.startsWith('foreman-') ? nameOrProject : sessionName(nameOrProject)
  const lastN = options?.lastN ?? 50

  // Try capture-pane first (live output)
  let output = ''
  try {
    output = tmuxRun(['capture-pane', '-t', name, '-p', '-S', `-${lastN}`])
  } catch {}

  // Fall back to log file
  if (!output.trim()) {
    const logFile = join(FOREMAN_HOME, 'logs', `session-${name}.log`)
    try {
      const log = readFileSync(logFile, 'utf8')
      const lines = log.split('\n')
      output = lines.slice(-lastN).join('\n')
    } catch {}
  }

  // Apply filters
  if (options?.pattern) {
    const regex = new RegExp(options.pattern, 'gi')
    output = output.split('\n').filter((l) => regex.test(l)).join('\n')
  }

  if (options?.codeOnly) {
    const codeBlocks: string[] = []
    const matches = output.matchAll(/```[\s\S]*?```/g)
    for (const m of matches) codeBlocks.push(m[0])
    output = codeBlocks.join('\n\n')
  }

  return output
}

// ─── Core: metrics ──────────────────────────────────────────────────

export function metrics(nameOrProject: string): SessionMetrics {
  const name = nameOrProject.startsWith('foreman-') ? nameOrProject : sessionName(nameOrProject)
  const info = getSessionInfo(name)
  const git = gitStat(info.projectPath)

  // Count test files
  let testsAdded = 0
  try {
    const testFiles = execFileSync('git', ['diff', '--name-only', '--diff-filter=A', 'HEAD~5..HEAD'], {
      cwd: info.projectPath, encoding: 'utf8', timeout: 5_000,
    })
    testsAdded = testFiles.split('\n').filter((f) => f.includes('test') || f.includes('spec')).length
  } catch {}

  return {
    commits: git.commits,
    linesAdded: git.linesAdded,
    linesRemoved: git.linesRemoved,
    filesChanged: git.filesChanged,
    testsAdded,
    rounds: info.round,
  }
}

// ─── Core: detect context exhaustion ────────────────────────────────

export function detectContextExhaustion(nameOrProject: string): boolean {
  const output = inspect(nameOrProject, { lastN: 20, pattern: 'Prompt is too long|context.*limit|max.*token|conversation.*too.*long' })
  return output.trim().length > 0
}

// ─── Core: kill ─────────────────────────────────────────────────────

export function kill(nameOrProject: string): boolean {
  const name = nameOrProject.startsWith('foreman-') ? nameOrProject : sessionName(nameOrProject)
  return tmuxRunQuiet(['kill-session', '-t', name])
}

export function killAll(): number {
  const sessions = status()
  let killed = 0
  for (const s of sessions) {
    if (kill(s.name)) killed++
  }
  return killed
}

// ─── Core: is alive ─────────────────────────────────────────────────

export function isAlive(nameOrProject: string): boolean {
  const name = nameOrProject.startsWith('foreman-') ? nameOrProject : sessionName(nameOrProject)
  return tmuxRunQuiet(['has-session', '-t', name])
}

// ─── Multi-round driver ─────────────────────────────────────────────

/**
 * Start a multi-round work session. Spawns claude, waits for it to
 * finish, checks progress, sends follow-up prompt, repeats.
 *
 * Unlike the bash driver script, this runs from Node and can inspect
 * output between rounds to make intelligent decisions.
 */
export async function driveProject(projectPath: string, options?: {
  maxRounds?: number
  onRound?: (round: number, metrics: SessionMetrics) => void
  onComplete?: (metrics: SessionMetrics) => void
}): Promise<SessionMetrics> {
  const maxRounds = options?.maxRounds ?? 20
  const name = sessionName(projectPath)

  // Spawn initial session
  spawn(projectPath)

  for (let round = 1; round <= maxRounds; round++) {
    // Wait for claude to finish (poll tmux pane for shell prompt)
    await waitForCompletion(name, 600_000) // 10 min max per round

    const m = metrics(name)
    options?.onRound?.(round, m)

    // Check for context exhaustion
    if (detectContextExhaustion(name)) {
      // Kill and respawn with fresh context
      kill(name)
      await sleep(2000)
      spawn(projectPath, buildPrompt(projectPath, round + 1))
      continue
    }

    // Check if done
    const stateFile = join(projectPath, '.foreman', 'session-state.md')
    if (existsSync(stateFile)) {
      const state = readFileSync(stateFile, 'utf8').toLowerCase()
      if (state.includes('done') || state.includes('production-ready') || state.includes('complete')) {
        break
      }
    }

    // Send next round
    const nextPrompt = buildPrompt(projectPath, round + 1)
    send(name, nextPrompt)
  }

  const finalMetrics = metrics(name)
  options?.onComplete?.(finalMetrics)
  return finalMetrics
}

async function waitForCompletion(name: string, timeoutMs: number): Promise<void> {
  const start = Date.now()
  while (Date.now() - start < timeoutMs) {
    await sleep(10_000) // check every 10s

    if (!isAlive(name)) return // session died

    // Check if the shell prompt is showing (claude finished)
    try {
      const lastLine = tmuxRun(['capture-pane', '-t', name, '-p', '-S', '-1']).trim()
      if (lastLine.endsWith('$') || lastLine.endsWith('#') || lastLine.includes('Session complete')) {
        return
      }
    } catch {}
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms))
}

// ─── Robot mode: JSON status ────────────────────────────────────────

export function robotStatus(): string {
  const sessions = status()
  return JSON.stringify({
    timestamp: new Date().toISOString(),
    sessions: sessions.map((s) => ({
      ...s,
      metrics: metrics(s.name),
      contextExhausted: s.alive ? detectContextExhaustion(s.name) : false,
    })),
    totalSessions: sessions.length,
    aliveSessions: sessions.filter((s) => s.alive).length,
  }, null, 2)
}
